version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  api:
    build: ./matia-project
    container_name: my-api
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  client:
    build: ./vite-project
    container_name: my-client
    ports:
      - 3002:3002
    depends_on:
      - api
volumes:
  mongo_data: